before_deploy:
- openssl aes-256-cbc -K $encrypted_f525f154c598_key -iv $encrypted_f525f154c598_iv
  -in id_rsa.enc -out id_rsa -d

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR $USER@$HOST:$PATH
  on:
    branch: master
