language: php

php:
  - 7.2

script: ""

before_deploy:
  - ssh-keyscan -t $TRAVIS_SSH_KEY_TYPES -H $REMOTE_HOST 2>&1 | tee -a $HOME/.ssh/known_hosts
  - echo -e "Host ${REMOTE_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_f525f154c598_key -iv $encrypted_f525f154c598_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - travis_retry composer self-update && composer install
  - travis_retry npm install && npm run prod

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete --exclude .env --exclude storage --exclude node_modules --quiet $TRAVIS_BUILD_DIR/ $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH >/dev/null 2>&1
  on:
    branch: master
